### ISSUE TITLE
MDContactNetwork frequencies have round down errors

### ISSUE THREAD

**Issue by akma327** [akma327/MDContactNetworks#8]
The latest version that computes the frequency of contacts for user had some inaccuracies in its contact freq. There is a bug in treating the "estimated" number of frame (round up to the nearest 100) as the actual total frame count, hence reported contact frequency is slightly off.

**Comment by RasmusFonseca** [comment]
Are you talking about an older commit, because I'm not aware that we compute frequencies in the latest. If you need frequencies theres a couple of ways to go about it. You can hack it in the terminal:
```bash
cd example
python3 ../dynamic_contacts.py --topology 5xnd_topology.pdb --trajectory 5xnd_trajectory.dcd --hbond --output 5xnd_hb.tsv
cut -f 1,3,4 5xnd_hb.tsv | sed 's/:[^:]*  /       /' | sed 's/:[^:]*$//' | sort | uniq | cut -f 2,3 | sort | uniq -c | sort -g
```
which prints the number of frames in which each pair of residue interactions occurred. I also added the outline of a script that computes residue contact frequencies in `Frequencies/contact_frequencies.py`:
```bash
cd example
python3 ../dynamic_contacts.py --topology 5xnd_topology.pdb --trajectory 5xnd_trajectory.dcd --hbond --output 5xnd_hb.tsv
python3 ../Frequencies/contact_frequencies.py --input 5xnd_hb.tsv --output 5xnd_hbfrequencies.tsv
```
which yields
```
A:GLN:53	A:GLN:69	0.65
A:GLU:60	A:SER:56	0.45
A:GLU:60	A:GLU:63	0.95
A:ARG:76	A:GLU:82	0.8
...
```
Theres currently no support for specifying interaction types or recording atomic frequencies but both should be pretty easy to add. 

It looks like theres a nice set of useful 'add-ons' beyond the Flareplots that we should figure out how to organize (MDCompare, Frequencies, TICC(?)). Maybe an `applications` sub-folder?

**Comment by akma327** [comment]
This is great Rasmus! Yes we can add options for atomic resolution and interaction types. 
I was thinking the same thing in terms of application plugins to MDCompare, networkx, flareplot, and TICC

**Comment by RasmusFonseca** [comment]
Bump .. is this resolved now?

**Comment by akma327** [comment]
Augustine brought up a good point I didn't account for earlier. After determining the number of unique frames in which an interaction occurs between two residues, how do you know what the denominator is? We dont yet have a way to extract exact num Frames of entire simulation.

**Comment by RasmusFonseca** [comment]
With the new `num_frames` argument this should be resolved now. I've updated the `Applications/contact_frequencies.py` script to use this value. MDCompare still needs to be updated, but that's no longer an issue for this repo ;) 

Close?

**Comment by akma327** [comment]
Yup! Thanks for taking care of this.
